title: Robert Vargas # your name (or website title) here
logo: "/images/Avatar.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <u><b>Business Intelligence Analyst</b></u>
  <br>
  Over 4 years of experience in business finance, accounting, and operations. My background includes forecasting, issuing financial statements, and trend analysis. I'm adept in general accounting principles (GAAP) and understanding the core processes significant to growth.
  <br><br>
  <a href="https://rpubs.com/Robato_95">View My RPubs Projects</a> 
  <br>
  <a href="https://public.tableau.com/profile/robert.vargas7196#!/">View My Tableau Portfolio</a> 
  <br><br>
  <a href="https://sites.google.com/d/1CNpZbeNRBvv4WIAcWpoPBhZ6vXscDKtD/p/1ZsAo5oOQSe8IFJ0MoD1LqMBufmUjLVsw/edit">RobatoBI Website</a>  
  
theme: jekyll-theme-minimal
google_analytics: G-0X9GCHKRC9 # your Google Analytics tracking ID here

