title: Robert Vargas # your name (or website title) here
logo: "/images/Avatar.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Business Intelligence Analyst
  <br>
  Over 4 years of experience in business finance, accounting, and operations. My background includes forecasting, issuing financial statements, and trend analysis. I am knowledgeable in general accounting principles (GAAP) and understanding the core processes required for growth.
  <br>
  <a href="https://rpubs.com/Robato_95">View My RPubs Projects</a> 
  <br>
  <a href="https://sites.google.com/d/1CNpZbeNRBvv4WIAcWpoPBhZ6vXscDKtD/p/1ZsAo5oOQSe8IFJ0MoD1LqMBufmUjLVsw/edit">RobatoBI Website</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

